### ISSUE TITLE
./SFStools.R -t mto2D -i early_geneflow

### ISSUE THREAD

**Issue by jingydz** [marqueda/SFS-scripts#1]
Hi,
When I try to run the SFStools.R, I get error message like this:

> [root@GenEngine bestrun]# ./SFStools.R -t mto2D -i early_geneflow

```
Read 4 items
Error in array(as.numeric(infile[-c(1, 2, 2 + 0:npop)]), rev(popsiz +  : 
  negative length vectors are not allowed
In addition: Warning message:
In as.integer(infile[2 + 1:npop]) : NAs introduced by coercion
Execution halted
```
![image](https://user-images.githubusercontent.com/45711930/65301449-2ac53000-dbaa-11e9-9c2f-13009434c26c.png)
Do you know what is the problem?

**Comment by marqueda** [comment]
Dear jingydz,

Not sure. Would you mind sending me your SFS file (something like early_geneflow_joint[MD]AF*_*.obs) by e-Mail to david.marques [at] eawag.ch? I will try to replicate the error and find the bug.

Best,
David

**Comment by marqueda** [comment]
Thank you for sending me the SFS file and reporting the issue, I was able to replicate the error and find the problem.

The issue was that the SFS file was not tab-delimited, but instead space-delimited, both for the population line and the SFS entries. Apparently, easySFS (https://github.com/isaacovercast/easySFS) was giving this space-delimited output. I recommend replacing the spaces with tabs (except in the first line) or instead using my vcf2sfs.py script, fastsimcol or arlequin for conversion between VCF and SFS format.

**Comment by jingydz** [comment]
Thank you for telling me.





------------------ 原始邮件 ------------------
发件人: "David Marques"<notifications@github.com>;
发送时间: 2019年9月20日(星期五) 晚上8:53
收件人: "marqueda/SFS-scripts"<SFS-scripts@noreply.github.com>;
抄送: "是个猿人！"<2604617551@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [marqueda/SFS-scripts] ./SFStools.R -t mto2D -i early_geneflow(#1)




Closed #1.

**Comment by yukiyukiyuki801** [comment]
Hello Dr. David Marques
I also got the error when using my own files (I have replaced all space to tab)
Would you mind providing me the example files of 2D obs and exp sfs for running  SFStools.R?
Thanks a lot 
and here are my 2D obs and exp sfs files
[sfs.zip](https://github.com/marqueda/SFS-scripts/files/11877249/sfs.zip)

**Comment by marqueda** [comment]
Your SFS files miss the header line ("1 observations"), see the fastsimcoal manual.

**Comment by marqueda** [comment]
Your 2D SFS files lack the header line ("1 observations"), see the fastsimcoal manual.

**Comment by Jiangjiangzhang6** [comment]
Hello Dr. David Marques, 
I run the comments " Rscript SFStools.R -t print2D -i pop30"
but its error 
Error in seq.default(log10(0.5), uplog, length.out = 100) :
  'to' must be a finite number
Calls: seq -> seq.default
In addition: Warning messages:
1: In max(c(obs, sim), na.rm = T) :
  no non-missing arguments to max; returning -Inf
2: In log10(max(c(obs, sim), na.rm = T) + 1e-05) : NaNs produced
Execution halted


how to debug, thank you
