### ISSUE TITLE
vcf2sfs

### ISSUE THREAD

**Issue by carolinapinapaez** [marqueda/SFS-scripts#3]
Hello Dr. Marques, 

I'm using your script to convert vcf to SFS. I was looking at the script and if there are more than 2 pops, the suffix == "_DSFS.obs"

I'm just curious about two things

1. Do I  need to manually change it from DSFS.obs to MSFS.obs? since DSFS.obs is for derived SFS and in my case, I don't know the ancestral state. 
2.  The only output file that I have is the DSFS.obs  but not he pairwise jointMAFpop1_0.obs...

Here is how I ran the script:
python vcf2sfs.py -i  87_NOMISS.vcf.gz -o 87_NOMISS -p 87_msia_pops.txt

Thanks for your help!
Carolina

**Comment by marqueda** [comment]
Dear Carolina,

1. You can use the foldSFS.py script to convert the unfolded SFS (DSFS.obs) into a folded SFS (MSFS.obs). I forgot to mention it in the README of this repository and just added it to the description now.
2. You can use the script SFStools.R with the command -t mto2D to get pairwise 2D-SFS from a multidimensional SFS file, which produces all the joint[D/M]AFpop1_o.obs etc. files, depending on if give the DSFS.obs or the MSFS.obs as input.

Best wishes,
David

**Comment by carolinapinapaez** [comment]
Wonderful! Thank you for the information.

Best,
Carolina
